# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145c60bae00544fcaf2f051214d2597924ada3134a0f4a1895b683a06c76105b07e5bda36c630127f3908a8541afdd79baf6433e7d6af096a39a4c4ad9fd36d7

test:
  secret_key_base: c525abe9688c971434c0ffad78e8ad6870fd3294030809c228bae4189be692ecd7638255820c62894ff7b95f67d7b0401612b6742135bcdbcb2a692bbfbdcf1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
